stages:
  - install
  - lint
  - build


cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - rm ./package-lock.json
    - npm install
  image: trion/ng-cli

lint:
  stage: lint
  script:
    - ng lint
  image: trion/ng-cli

build:
  stage: build
  script:
    - ng build --prod
  image: trion/ng-cli
