stages:
  - install
  - lint
  - build
  - publish


cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - rm ./package-lock.json
    - npm install
  image: trion/ng-cli

lint:
  stage: lint
  script:
    - ng lint
  image: trion/ng-cli

build:
  stage: build
  script:
    - ng config -g cli.warnings.versionMismatch false
    - ng build --prod
  image: trion/ng-cli

publish:
  stage: publish
  script:
    - ng build --prod
    - docker build -t localhost:5000/freelance-bordeaux:latest .
    - docker push localhost:5000/freelance-bordeaux:latest
  image: docker
